---
first-app:
  start_cmd   : 'true'
  stop_cmd    : 'true'
  status_cmd  : 'true'
  list_cmd    : 'command,echo "1.0 2.0 3.0 4.0 5.0"'
  deploy_cmd  : 'true'
  version_cmd : 'echo 1.0'
  log_file    : 'conf/example.log'
second-app:
   start_cmd   : 'true'
   stop_cmd    : 'false'
   status_cmd  : 'true'
   list_cmd    : 'nexus,http://maven.innoveo.com:8081/nexus,com.innoveo,innoveo-skye-shared-bundle'
   deploy_cmd  : 'false'
   version_cmd : 'true'
   log_file    : 'conf/example.log'
third-app:
  start_cmd   : 'service tomcat start'
  stop_cmd    : 'service tomcat stop'
